const DEPARTMENTS  = [
  "General Medicine",
  "General Surgery",
  "Cardiology",
  "Neurology",
  "Neurosurgery",
  "Orthopedics",
  "Pediatrics",
  "Gynecology & Obstetrics",
  "Dermatology",
  "ENT",
  "Ophthalmology",
  "Urology",
  "Nephrology",
  "Gastroenterology",
  "Oncology",
  "Pulmonology",
  "Endocrinology",
  "Psychiatry",
  "Rheumatology",
  "Dentistry",
  "Physiotherapy",
  "Plastic Surgery",
  "Anesthesiology",
  "Pain Management",
  "Allergy & Immunology",
  "Infectious Diseases",
  "Family Medicine",
  "Geriatrics",
  "Sports Medicine",
  "Nutrition & Dietetics"
];

module.exports = DEPARTMENTS;